#!/bin/bash

if [ $# -eq 0 ]
then
    folder="latex-project"
else
    folder=$1
fi


mkdir $folder > /dev/null
cd $folder
cp -a $HOME/bin/shell-scripts/latex-files/. .
git init
git clone https://github.com/odinase/.vscode-cheat.git
mv .vscode-cheat .vscode
code .
